repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files
  - id: check-ast
  - id: check-json
  - id: end-of-file-fixer
  - id: name-tests-test
  - id: no-commit-to-branch
  - id: pretty-format-json
  - id: requirements-txt-fixer
  - id: trailing-whitespace

- repo: https://github.com/timothycrosley/isort
  rev: 5.12.0
  hooks:
  - id: isort
    args: ["--profile", "black", "--filter-files"]

- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
  - id: black
    language_version: python3.11

- repo: https://github.com/pycqa/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
    entry: bash -c 'flake8 "$@" || true' --
    args: [--max-line-length=100]
    verbose: true

- repo: https://github.com/PyCQA/bandit
  rev: 1.7.5
  hooks:
  - id: bandit
    entry: bash -c 'bandit "$@" || true' --

- repo: https://github.com/asottile/pyupgrade
  rev: v3.7.0
  hooks:
  - id: pyupgrade
    args: [--py36-plus]
